# Generated by Django 5.2.7 on 2025-10-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnesstrack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fitnessitem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='fitnessitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
