# Generated by Django 4.2.7 on 2026-02-12 17:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitnesstrack', '0002_remove_fitnessitem_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('RUNNING', 'Running'), ('CYCLING', 'Cycling'), ('WEIGHTLIFTING', 'Weightlifting'), ('SWIMMING', 'Swimming'), ('WALKING', 'Walking'), ('YOGA', 'Yoga'), ('HIIT', 'HIIT'), ('OTHER', 'Other')], help_text='Type of physical activity', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of activity in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distance covered in kilometers (if applicable)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('calories_burned', models.PositiveIntegerField(blank=True, help_text='Estimated calories burned during activity', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the activity')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='BiometricsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('body_fat_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Body fat percentage', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('muscle_mass_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Muscle mass in kilograms', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('waist_circumference_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Waist circumference in centimeters', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, help_text='Additional observations')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometrics_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Biometrics Log',
                'verbose_name_plural': 'Biometrics Logs',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('WEIGHT', 'Target Weight'), ('WEEKLY_STEPS', 'Weekly Steps'), ('MONTHLY_DISTANCE', 'Monthly Distance'), ('BODY_FAT', 'Body Fat Percentage'), ('MUSCLE_GAIN', 'Muscle Gain'), ('EXERCISE_FREQUENCY', 'Exercise Frequency'), ('WATER_INTAKE', 'Daily Water Intake'), ('OTHER', 'Other')], help_text='Type of fitness goal', max_length=20)),
                ('title', models.CharField(help_text='Goal title or description', max_length=200)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Target numerical value', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current progress value', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('unit', models.CharField(default='units', help_text='Unit of measurement (kg, km, steps, %, etc.)', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('target_date', models.DateField(blank=True, help_text='Target completion date', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional goal details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Goal',
                'verbose_name_plural': 'Goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, help_text="User's date of birth", null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Current weight in kilograms', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('activity_level', models.CharField(choices=[('SEDENTARY', 'Sedentary'), ('ACTIVE', 'Active'), ('ATHLETE', 'Athlete')], default='SEDENTARY', help_text='General activity level', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milliliters', models.PositiveIntegerField(help_text='Amount of water in milliliters', validators=[django.core.validators.MinValueValidator(1)])),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, help_text='Optional notes (e.g., type of beverage)', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Water Intake',
                'verbose_name_plural': 'Water Intakes',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.DeleteModel(
            name='FitnessItem',
        ),
        migrations.AddIndex(
            model_name='waterintake',
            index=models.Index(fields=['-date_recorded', 'user'], name='fitnesstrac_date_re_0d755f_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'status'], name='fitnesstrac_user_id_7509ff_idx'),
        ),
        migrations.AddIndex(
            model_name='biometricslog',
            index=models.Index(fields=['-date_recorded', 'user'], name='fitnesstrac_date_re_c0f769_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-date_created', 'user'], name='fitnesstrac_date_cr_6538c6_idx'),
        ),
    ]
