# Generated by Django 4.2.7 on 2026-02-13 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitnesstrack', '0003_activitylog_biometricslog_goal_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('CONSISTENCY_7', '7-Day Consistency'), ('CONSISTENCY_30', '30-Day Consistency'), ('FIRST_WORKOUT', 'First Workout'), ('CALORIE_BURNER_1000', '1000 Calories Burned'), ('CALORIE_BURNER_5000', '5000 Calories Burned'), ('EARLY_BIRD', 'Early Bird (Workout before 7 AM)'), ('HYDRATION_MASTER', 'Hydration Master'), ('WEIGHT_GOAL', 'Weight Goal Achieved')], help_text='Type of achievement badge', max_length=30)),
                ('earned_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text='Achievement description', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Badge',
                'verbose_name_plural': 'Badges',
                'ordering': ['-earned_date'],
                'indexes': [models.Index(fields=['user', 'badge_type'], name='fitnesstrac_user_id_11d504_idx')],
                'unique_together': {('user', 'badge_type')},
            },
        ),
    ]
