# Generated by Django 4.2.7 on 2026-02-13 06:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitnesstrack', '0004_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], default='BREAKFAST', max_length=20)),
                ('food_name', models.CharField(help_text='Name of the food/meal', max_length=255)),
                ('calories', models.IntegerField(help_text='Calories in kcal', validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_g', models.DecimalField(decimal_places=1, default=0, help_text='Protein in grams', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('carbs_g', models.DecimalField(decimal_places=1, default=0, help_text='Carbohydrates in grams', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fats_g', models.DecimalField(decimal_places=1, default=0, help_text='Fats in grams', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('serving_size', models.CharField(blank=True, help_text="e.g., '1 cup', '100g', '1 serving'", max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_logged', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_logged'],
                'indexes': [models.Index(fields=['user', '-date_logged'], name='fitnesstrac_user_id_43d6d9_idx')],
            },
        ),
    ]
